CREATE TABLE IF NOT EXISTS "receta" (
	"id_receta" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(50) NOT NULL,
	"descripcion" VARCHAR(255) NOT NULL,
	"ingredientes" TEXT NOT NULL,
	"id_usuario" INTEGER NOT NULL,
	"pasos" TEXT NOT NULL,
	PRIMARY KEY("id_receta")
);

CREATE TABLE IF NOT EXISTS "usuario" (
	"id_usuario" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"contrasenia" VARCHAR(255) NOT NULL,
	"nombre" VARCHAR(255) NOT NULL,
	"apellido" VARCHAR(255),
	"email" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("id_usuario")
);

CREATE TABLE IF NOT EXISTS "comentario" (
	"id_usuario" INTEGER NOT NULL,
	"id_receta" INTEGER NOT NULL,
    "id_comentario" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"descripcion" VARCHAR(255) NOT NULL,
	"puntuacion" SMALLINT NOT NULL CHECK (puntuacion BETWEEN 1 AND 5),
	PRIMARY KEY("id_comentario")
);

ALTER TABLE "comentario"
ADD FOREIGN KEY("id_receta") REFERENCES "receta"("id_receta")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "receta"
ADD FOREIGN KEY("id_usuario") REFERENCES "usuario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "comentario"
ADD FOREIGN KEY("id_usuario") REFERENCES "usuario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;