services:
  database:
    image: postgres:18
    environment:
      POSTGRES_DB: recetas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d recetas"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  postgres_data:
