services:
  database:
    image: postgres:18
    environment:
      POSTGRES_DB: recetas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
