CREATE TABLE IF NOT EXISTS "receta" (
	"id_receta" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(50) NOT NULL,
	"descripcion" VARCHAR(255) NOT NULL,
	"id_usuario" INTEGER NOT NULL,
	"pasos" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_receta")
);

CREATE TABLE IF NOT EXISTS "usuario" (
	"id_usuario" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"contraseña" VARCHAR(255) NOT NULL,
	"nombre" VARCHAR(255) NOT NULL,
	"apellido" VARCHAR(255),
	"email" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_usuario")
);

CREATE TABLE IF NOT EXISTS "ingrediente" (
	"id_ingrediente" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_ingrediente")
);

CREATE TABLE IF NOT EXISTS "receta_ingrediente" (
	"id_receta" INTEGER NOT NULL,
	"id_ingrediente" INTEGER NOT NULL,
	"cantidad" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_receta", "id_ingrediente")
);

CREATE TABLE IF NOT EXISTS "comentario" (
	"id_usuario" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_receta" INTEGER NOT NULL,
	"descripcion" VARCHAR(255) NOT NULL,
	"puntuacion" SMALLINT NOT NULL,
	PRIMARY KEY("id_usuario", "id_receta")
);

ALTER TABLE "receta"
ADD FOREIGN KEY("id_receta") REFERENCES "receta_ingrediente"("id_receta")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ingrediente"
ADD FOREIGN KEY("id_ingrediente") REFERENCES "receta_ingrediente"("id_ingrediente")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "comentario"
ADD FOREIGN KEY("id_receta") REFERENCES "receta"("id_receta")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "usuario"
ADD FOREIGN KEY("id_usuario") REFERENCES "receta"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "usuario"
ADD FOREIGN KEY("id_usuario") REFERENCES "comentario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;